# Site settings
title: Try jekylltitle
email: erimerturk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn new things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iddaala.net" # the base hostname & protocol for your site
twitter_username: erimerturk
github_username:  erimerturk

# Build settings
markdown: kramdown
